spring:
  application:
    name: task
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:demo_data.sql
      continue-on-error: false # Лучше упасть, чем запустить кривую базу