spring:
  application:
    name: task
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:demo_data.sql
      continue-on-error: false
security:
  jwt:
    secret: YXNkYXNkenhkMTIzMTI0MzIhfn4xIUA0MTI0cWYxMzIzZjJ0
    access: 3600000
    refresh: 2592000000